config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :books, only: %i[index new create update]
  resources :authors, only: %i[new create]

  root 'books#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :books, dependent: :nullify

  validates :name, presence: true
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :author

  validates :name, presence: true
  validates :year, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
# frozen_string_literal: true

class AuthorsController < ApplicationController
  # GET /authors/new
  def new
    @author = Author.new
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to new_book_path, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use strong parameters to restrict attributes that can be changed
  def author_params
    params.require(:author).permit(:name)
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :find_book, only: :update

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to books_path, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to books_path, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def find_book
    @book = Book.find(params[:id])
  end

  # Use strong parameters to restrict attributes that can be changed
  def book_params
    params.require(:book).permit(:name, :author_id, :favorite, :year)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/authors_helper.rb
# frozen_string_literal: true

module AuthorsHelper
end

app/helpers/books_helper.rb
# frozen_string_literal: true

module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', {class: 'button button-submit'} %>
  </div>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', new_book_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.select :author_id, Author.all.pluck(:name, :id) %>
    or 
    <%= link_to 'add new', new_author_path %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>


  <div class="actions">
    <%= form.submit "Submit", {class: 'button button-submit'} %>
  </div>
<% end %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h2>Books</h2>
  <%= link_to 'New Book', new_book_path, {class: 'button button-header'} %>
</div>

<div class="cards-container">
  <% @books.each do |book| %>
    <div class="book-card" data-controller="book">
      <h3 class="card-heading"><%= book.name %></h3>
      <h4 class="card-subheading">Author: <strong><%= book.author.name %></strong></h4>
      <h4 class="card-subheading">Year: <strong><%= book.year %></strong></h4>
      <div class="form-group">
        <label class="favorite-label" for=<%= "favorite-#{book.id}"%>>Favorite</label>
        <input
          type=checkbox
          id=<%= "favorite-#{book.id}"%>
          name=<%= "favorite-#{book.id}"%>
          <%= "checked" if book.favorite? %>
          data-book-id=<%= book.id %>
          data-action="book#toggleFavorite"
        />
      </div>
    </div>
  <% end %>
</div>

<br>

app/views/books/new.html.erb
<div class="page-header">
  <h2>New Book</h2>
</div>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book List</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="header">
      <h1>
        <a href="/" class="header-logo">Book List</a>
      </h1>
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
  </body>
</html>